version: '3'

services:

  fakecoin:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - 8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.4-management
    ports:
      - 5671:5671
      - 15672:15672
      - 25672:25672

